<a href="https://colab.research.google.com/github/Harshitha1588/Python_2303A51588_B10/blob/main/Lab3_1588.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Perform basic arithmetic operations like addition and subtraction
on 2D NumPy arrays representing matrices

In [1]:
import numpy as np
A=np.array([[20,30,40],[40,50,60]])
B=np.array([[15,10,25],[20,25,35]])
print(A)
print(B)


[[20 30 40]
 [40 50 60]]
[[15 10 25]
 [20 25 35]]


In [2]:
addition=np.add(A,B)
print(addition)
subtraction=np.subtract(A,B)
print(subtraction)

[[35 40 65]
 [60 75 95]]
[[ 5 20 15]
 [20 25 25]]


Apply statistical operations like mean, median, std, min, and max
to analyze 2D array data.

In [3]:
import numpy as np
scores = np.random.randint(0, 101, (4, 4))
print("Test Scores (4x4):\n", scores)
row_mean = np.mean(scores, axis=1)
print("\nRow-wise Mean (per student):\n", row_mean)
col_mean = np.mean(scores, axis=0)
print("\nColumn-wise Mean (per subject):\n", col_mean)
std_dev = np.std(scores)
variance = np.var(scores)
print("\nStandard Deviation of all scores:", std_dev)
print("Variance of all scores:", variance)
max_value = np.max(scores)
min_value = np.min(scores)
max_index = np.unravel_index(np.argmax(scores), scores.shape)
min_index = np.unravel_index(np.argmin(scores), scores.shape)
print("\nMaximum Score:", max_value)
print("Minimum Score:", min_value)

Test Scores (4x4):
 [[ 93  79  88  19]
 [ 11 100  84  25]
 [ 52  53  94  72]
 [ 93   2  64  56]]

Row-wise Mean (per student):
 [69.75 55.   67.75 53.75]

Column-wise Mean (per subject):
 [62.25 58.5  82.5  43.  ]

Standard Deviation of all scores: 31.200898925351495
Variance of all scores: 973.49609375

Maximum Score: 100
Minimum Score: 2


Apply statistical operations like mean, median, std, min, and max
to analyze 2D array data

In [4]:
import numpy as np
image = np.random.randint(0, 256, (3, 3, 3))
print("Original Image:\n", image)
red   = image[:, :, 0]
green = image[:, :, 1]
blue  = image[:, :, 2]
print("\nRed Channel:\n", red)
print("\nGreen Channel:\n", green)
print("\nBlue Channel:\n", blue)
print("\nAverage Red:", np.mean(red))
print("Average Green:", np.mean(green))
print("Average Blue:", np.mean(blue))
bright = np.clip(np.add(image, 50), 0, 255)
print("\nBrightened Image:\n", bright)
dark = np.clip(np.subtract(image, 50), 0, 255)
print("\nDarkened Image:\n", dark)


Original Image:
 [[[189 241  22]
  [ 70 242 122]
  [ 46 164  74]]

 [[199 118  75]
  [147 236 218]
  [126  51 109]]

 [[169 242 132]
  [131  95 171]
  [166  55 126]]]

Red Channel:
 [[189  70  46]
 [199 147 126]
 [169 131 166]]

Green Channel:
 [[241 242 164]
 [118 236  51]
 [242  95  55]]

Blue Channel:
 [[ 22 122  74]
 [ 75 218 109]
 [132 171 126]]

Average Red: 138.11111111111111
Average Green: 160.44444444444446
Average Blue: 116.55555555555556

Brightened Image:
 [[[239 255  72]
  [120 255 172]
  [ 96 214 124]]

 [[249 168 125]
  [197 255 255]
  [176 101 159]]

 [[219 255 182]
  [181 145 221]
  [216 105 176]]]

Darkened Image:
 [[[139 191   0]
  [ 20 192  72]
  [  0 114  24]]

 [[149  68  25]
  [ 97 186 168]
  [ 76   1  59]]

 [[119 192  82]
  [ 81  45 121]
  [116   5  76]]]
