<a href="https://colab.research.google.com/github/Harshitha1588/Python_2303A51588_B10/blob/main/Python_Lab_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
arr=np.array(['python','cloud computing','sesd'])
marks=np.array([[80,90,75],[76,82,95],[86,95,90],[75,80,68],[81,68,82]])
print(arr)
print(marks)

['python' 'cloud computing' 'sesd']
[[80 90 75]
 [76 82 95]
 [86 95 90]
 [75 80 68]
 [81 68 82]]


In [ ]:
average=marks.mean()
minimum=marks.min()
maximum=marks.max()
print("Average Marks:",average)
print("Minimum Marks:",minimum)
print("Maximium Marks:",maximum)

Average Marks: 81.53333333333333
Minimum Marks: 68
Maximium Marks: 95


In [ ]:
print("Marks of Student 1:",marks[0, :])
print("Marks of Student 2:",marks[1, :])
print("Marks of Student 3:",marks[2, :])
print("Marks of Student 4:",marks[3, :])
print("Marks of Student 5:",marks[4, :])



Marks of Student 1: [80 90 75]
Marks of Student 2: [76 82 95]
Marks of Student 3: [86 95 90]
Marks of Student 4: [75 80 68]
Marks of Student 5: [81 68 82]


In [ ]:
Students_above_80=marks>80
print("Students with marks above 80:",marks[Students_above_80])

Students with marks above 80: [90 82 95 86 95 90 81 82]


In [ ]:
reshape=marks.T
print("Subject-wise Marks:")
print(reshape)

Subject-wise Marks:
[[80 76 86 75 81]
 [90 82 95 80 68]
 [75 95 90 68 82]]


2.*Question* : Employee salary analysis

In [ ]:
import pandas as pd

In [ ]:
dataframe={'Name':['Anjali','Rajesh','Sumathi','Harish','Raji'],
           'ID':[101,102,103,104,105],
           'Department':['HR','IT','Finance','Marketing','IT'],
           'Salary':[60000,75000,55000,80000,48000]}
df=pd.DataFrame(dataframe)
print(df)

      Name   ID Department  Salary
0   Anjali  101         HR   60000
1   Rajesh  102         IT   75000
2  Sumathi  103    Finance   55000
3   Harish  104  Marketing   80000
4     Raji  105         IT   48000


In [ ]:
high_Salary=df[df['Salary']>50000]
print("Employees with salary greater than 50000:")
print(high_Salary)

Employees with salary greater than 50000:
      Name   ID Department  Salary
0   Anjali  101         HR   60000
1   Rajesh  102         IT   75000
2  Sumathi  103    Finance   55000
3   Harish  104  Marketing   80000


In [ ]:
descending_order=df.sort_values(by='Salary',ascending=False)
print("Employees in descending order of salary:")
print(descending_order)

Employees in descending order of salary:
      Name   ID Department  Salary
3   Harish  104  Marketing   80000
1   Rajesh  102         IT   75000
0   Anjali  101         HR   60000
2  Sumathi  103    Finance   55000
4     Raji  105         IT   48000


In [ ]:
df['Bonus']=df['Salary']*0.10
print(df)

      Name   ID Department  Salary   Bonus
0   Anjali  101         HR   60000  6000.0
1   Rajesh  102         IT   75000  7500.0
2  Sumathi  103    Finance   55000  5500.0
3   Harish  104  Marketing   80000  8000.0
4     Raji  105         IT   48000  4800.0


In [ ]:
df['Total_Compensation']=df['Salary']+df['Bonus']
print(df)
Total_expenses=df['Total_Compensation'].sum()
print("Total Salary Expenditure:",Total_expenses)


      Name   ID Department  Salary   Bonus  Total_Compensation
0   Anjali  101         HR   60000  6000.0             66000.0
1   Rajesh  102         IT   75000  7500.0             82500.0
2  Sumathi  103    Finance   55000  5500.0             60500.0
3   Harish  104  Marketing   80000  8000.0             88000.0
4     Raji  105         IT   48000  4800.0             52800.0
Total Salary Expenditure: 349800.0


In [ ]:
df.to_csv("employee_salary_analysis.csv", index=False)