<a href="https://colab.research.google.com/github/Harshitha1588/Python_2303A51588_B10/blob/main/Python_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [6]:
arr2D_1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2D_2=np.array([[10,11,12],[13,14,15],[16,17,18]])
print("2D Array 1:\n",arr2D_1)
print("2D Array 2:\n",arr2D_2)

2D Array 1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
2D Array 2:
 [[10 11 12]
 [13 14 15]
 [16 17 18]]


In [9]:
add_result=np.add(arr2D_1,arr2D_2)
sub_result=np.subtract(arr2D_1,arr2D_2)
print("Addition:\n",add_result)
print("Substraction:\n",sub_result)

Addition:
 [[11 13 15]
 [17 19 21]
 [23 25 27]]
Substraction:
 [[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]


2D Matrix Multiplication

In [11]:
import numpy as np
import pandas as pd

In [12]:
arr_1=np.array([[4,5],[2,5],[2,4]])
arr_2=np.array([[1,2,3],[4,5,6]])
print("2D Array 1:\n",arr_1)
print("2D Array 2:\n",arr_2)

2D Array 1:
 [[4 5]
 [2 5]
 [2 4]]
2D Array 2:
 [[1 2 3]
 [4 5 6]]


In [13]:
result=np.dot(arr_1,arr_2)
print("Dot product:\n",result)

Dot product:
 [[24 33 42]
 [22 29 36]
 [18 24 30]]
